
# Gaia and I/O
gaia:
  username: "jcrans"      # or set explicitly here
  password: "2]#x~X_$,}qHxE="      # or set explicitly here
  tap_url: "https://gea.esac.esa.int/tap-server/tap"
data:
  source_id_list: "inputs/source_ids.csv"   # CSV with a 'source_id' column
  outdir: "outputs"
  cache_dir: "outputs/cache"
  overwrite: false

# Extraction
extraction:
  min_points: 24

# Frequency search
frequency_search:
  min_freq: 0
  max_freq: 360.0
  oversample: 10

# Feature engineering
features:
  augment_with_gaia_summary: true

# Dimensionality reduction & clustering
ml:
  correlation_threshold: 0.95
  tsne:
    perplexity_grid: [30,50]
    learning_rate_grid: [200,300]
    n_iter: 1000
    metric: "euclidean"
    random_state: 42
  gmm:
    n_components_grid: [3,4]
    covariance_type: 'spherical'
    n_init: 10
    random_state: 42
  rf_prune:
    enabled: true
    n_estimators: 100
    top_k_features: 60
    random_state: 42

# Visualization
viz:
  tsne_scatter: true
  feature_importances: true
